"""empty message

Revision ID: 0c47e7bd58a4
Revises: bcee3fc15d4c
Create Date: 2024-10-06 04:15:43.371108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c47e7bd58a4'
down_revision = 'bcee3fc15d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_column('recommended')

    # ### end Alembic commands ###
