"""Remove recommended column from BlogPost

Revision ID: e4efa9456ec6
Revises: 2cd62d57a2e9
Create Date: 2024-10-06 19:02:24.336018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4efa9456ec6'
down_revision = '2cd62d57a2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BlogPost', schema=None) as batch_op:
        batch_op.drop_column('recommended')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('BlogPost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###
